export const PLAYER = {
  ACCELERATION: 60,
  MAX_SPEED: 22,
  DAMPING: 3,
  BOUNDS_X: 14,
  BOUNDS_Y: 10,
  SHOOT_COOLDOWN: 0.15,
  BULLET_SPEED: 80,
  COLLISION_RADIUS: 2.0,
  INVINCIBLE_DURATION: 2.0,
  FORWARD_SPEED: 30,
  TILT_FACTOR_X: 0.06,
  TILT_FACTOR_Y: 0.04,
  TILT_LERP: 4,
} as const;

export const ASTEROID = {
  BASE_SPEED: 15,
  SPEED_PER_LEVEL: 3,
  BASE_SPAWN_INTERVAL: 1.5,
  SPAWN_INTERVAL_DECAY: 0.1,
  MIN_SPAWN_INTERVAL: 0.3,
  BASE_COUNT: 2,
  COUNT_PER_LEVEL: 1,
  DESTROY_FOR_NEXT_LEVEL: 20,
  SPAWN_DISTANCE: 120,
  DESPAWN_DISTANCE: 30,
  MIN_RADIUS: 1.5,
  MAX_RADIUS: 5.0,
} as const;

export const EFFECTS = {
  EXPLOSION_DURATION: 0.6,
  EXPLOSION_PARTICLES: 15,
  SCREEN_SHAKE_INTENSITY: 0.4,
  SCREEN_SHAKE_DECAY: 4.0,
} as const;

export const AMMO = {
  MAX: 30,
  START: 30,
  RELOAD_AMOUNT: 15,
  RING_SPACING: 60,
  RING_COUNT: 3,
  RING_COLLECT_RADIUS: 8,
} as const;

export const RADAR = {
  SIZE: 160,
  RANGE: 100,
} as const;

export const CAMERA = {
  OFFSET_Y: 6,
  OFFSET_Z: 14,
  LOOK_AHEAD: 20,
  LERP_SPEED: 3,
} as const;
